accent = "#e6b450"
panel_bg = "reset"
sidebar_bg = "reset"
active_row_bg = "#272c36"
selection_bg = "#2f3542"
surface0 = "#272c36"
surface1 = "#2f3542"
surface_dim = "#040507"
overlay0 = "#595f6a"
overlay1 = "#8e959e"
text = "#d1d1c7"
subtext0 = "#8e959e"
mauve = "#cda1fa"
green = "#7fd962"
yellow = "#f9af4f"
red = "#ea6c73"
blue = "#53bdfa"
teal = "#90e1c6"
peach = "#eaa46c"
