# BEGIN_KITTY_THEME
include theme.conf


font_family CaskaydiaCove Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14

background_opacity 0.9
hide_window_decorations no
linux_display_server wayland
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

remember_window_size  yes
initial_window_width  640
initial_window_height 400

tab_bar_edge bottom
tab_bar_margin_width 0.0
tab_bar_style slant