[mgr]
cwd = { fg = "#83c092" }

# Hovered
hovered         = { fg = "#2d353b", bg = "#7fbbb3" }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#dbbc7f", italic = true }
find_position = { fg = "#d699b6", bg = "reset", italic = true }

# Marker
marker_copied   = { fg = "#a7c080", bg = "#a7c080" }
marker_cut      = { fg = "#e67e80", bg = "#e67e80" }
marker_selected = { fg = "#7fbbb3", bg = "#7fbbb3" }

# Tab
tab_active   = { fg = "#2d353b", bg = "#d3c6aa" }
tab_inactive = { fg = "#d3c6aa", bg = "#3d484d" }
tab_width    = 1

# Count
count_copied   = { fg = "#2d353b", bg = "#a7c080" }
count_cut      = { fg = "#2d353b", bg = "#e67e80" }
count_selected = { fg = "#2d353b", bg = "#7fbbb3" }

# Border
border_symbol = "│"
border_style  = { fg = "#56635f" }

# Highlighting
syntect_theme = "~/.config/yazi/Everforest-dark.tmTheme"

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#3d484d", bg = "#3d484d" }

# Mode
mode_normal = { fg = "#2d353b", bg = "#7fbbb3", bold = true }
mode_select = { fg = "#2d353b", bg = "#a7c080", bold = true }
mode_unset  = { fg = "#2d353b", bg = "#e69875", bold = true }

# Progress
progress_label  = { fg = "#d3c6aa", bold = true }
progress_normal = { fg = "#7fbbb3", bg = "#3d484d" }
progress_error  = { fg = "#e67e80", bg = "#3d484d" }

# Permissions
permissions_t = { fg = "#7fbbb3" }
permissions_r = { fg = "#dbbc7f" }
permissions_w = { fg = "#e67e80" }
permissions_x = { fg = "#a7c080" }
permissions_s = { fg = "#56635f" }

[input]
border   = { fg = "#7fbbb3" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#7fbbb3" }
active   = { fg = "#d699b6" }
inactive = {}

[tasks]
border  = { fg = "#7fbbb3" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#343f44" }
cand            = { fg = "#83c092" }
rest            = { fg = "#7a8478" }
desc            = { fg = "#d699b6" }
separator       = "  "
separator_style = { fg = "#475258" }

[help]
on      = { fg = "#d699b6" }
exec    = { fg = "#83c092" }
desc    = { fg = "#7a8478" }
hovered = { bg = "#475258", bold = true }
footer  = { fg = "#3d484d", bg = "#d3c6aa" }

[filetype]

rules = [
	# Media
	{ mime = "image/*", fg = "#83c092" },
	{ mime = "{audio,video}/*", fg = "#dbbc7f" },

	# Archives
  { mime = "application/{,g}zip", fg = "#d699b6" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#d699b6" },

	# Fallback
	{ name = "*", fg = "#d3c6aa" },
	{ name = "*/", fg = "#7fbbb3" }
]

[icon]

files = [
  { name = "gulpfile.js", text = "", fg_dark = "#e67e80", fg_light = "#e67e80" },
  { name = ".babelrc", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = "copying.lesser", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = ".npmrc", text = "", fg_dark = "#e67e80", fg_light = "#e67e80" },
  { name = "docker-compose.yml", text = "󰡨", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = "svelte.config.js", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "copying", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = "prettier.config.ts", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = "gruntfile.babel.js", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = ".SRCINFO", text = "󰣇", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = ".xinitrc", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "docker-compose.yaml", text = "󰡨", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = "nuxt.config.ts", text = "󱄆", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = "build", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = ".editorconfig", text = "", fg_dark = "#d3c6aa", fg_light = "#d3c6aa" },
  { name = "nuxt.config.mjs", text = "󱄆", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = ".gitlab-ci.yml", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "PKGBUILD", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = ".bash_profile", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = ".bashrc", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = "compose.yml", text = "󰡨", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = "eslint.config.cjs", text = "", fg_dark = "#475258", fg_light = "#475258" },
  { name = "go.mod", text = "", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = ".mailmap", text = "󰊢", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "gtkrc", text = "", fg_dark = "#d3c6aa", fg_light = "#d3c6aa" },
  { name = "go.work", text = "", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = "justfile", text = "", fg_dark = "#56635f", fg_light = "#56635f" },
  { name = "kritadisplayrc", text = "", fg_dark = "#d699b6", fg_light = "#d699b6" },
  { name = "commitlint.config.js", text = "󰜘", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = ".env", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = "PrusaSlicerGcodeViewer.ini", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "r", text = "󰟔", fg_dark = "#4f585e", fg_light = "#4f585e" },
  { name = "license", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = ".gitignore", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "tailwind.config.js", text = "󱏿", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = ".prettierrc.yml", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = ".zprofile", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = ".zshenv", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = "xmonad.hs", text = "", fg_dark = "#e67e80", fg_light = "#e67e80" },
  { name = ".eslintignore", text = "", fg_dark = "#475258", fg_light = "#475258" },
  { name = "tsconfig.json", text = "", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = ".prettierrc.json5", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = ".ds_store", text = "", fg_dark = "#3d484d", fg_light = "#3d484d" },
  { name = "gulpfile.coffee", text = "", fg_dark = "#e67e80", fg_light = "#e67e80" },
  { name = "R", text = "󰟔", fg_dark = "#4f585e", fg_light = "#4f585e" },
  { name = ".zshrc", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = ".prettierrc.toml", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = ".gvimrc", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = ".xsession", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = ".justfile", text = "", fg_dark = "#56635f", fg_light = "#56635f" },
  { name = ".gitconfig", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "gradle-wrapper.properties", text = "", fg_dark = "#475258", fg_light = "#475258" },
  { name = "ionic.config.json", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = "cantorrc", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = ".gleam", text = "", fg_dark = "#d699b6", fg_light = "#d699b6" },
  { name = "package-lock.json", text = "", fg_dark = "#343f44", fg_light = "#343f44" },
  { name = "package.json", text = "", fg_dark = "#e67e80", fg_light = "#e67e80" },
  { name = "hyprland.conf", text = "", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = "gulpfile.babel.js", text = "", fg_dark = "#e67e80", fg_light = "#e67e80" },
  { name = ".nvmrc", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = ".prettierignore", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = "ext_typoscript_setup.txt", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "QtProject.conf", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = "avif", text = "", fg_dark = "#56635f", fg_light = "#56635f" },
  { name = "mix.lock", text = "", fg_dark = "#56635f", fg_light = "#56635f" },
  { name = "build.gradle", text = "", fg_dark = "#475258", fg_light = "#475258" },
  { name = "gemfile$", text = "", fg_dark = "#343f44", fg_light = "#343f44" },
  { name = ".vimrc", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = "i18n.config.ts", text = "󰗊", fg_dark = "#56635f", fg_light = "#56635f" },
  { name = "gulpfile.ts", text = "", fg_dark = "#e67e80", fg_light = "#e67e80" },
  { name = "build.zig.zon", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "checkhealth", text = "󰓙", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = "xmobarrc", text = "", fg_dark = "#e67e80", fg_light = "#e67e80" },
  { name = "_vimrc", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = ".luaurc", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = "kdenlive-layoutsrc", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = "gradlew", text = "", fg_dark = "#475258", fg_light = "#475258" },
  { name = "xsettingsd.conf", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "vlcrc", text = "󰕼", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "xorg.conf", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "xmobarrc.hs", text = "", fg_dark = "#e67e80", fg_light = "#e67e80" },
  { name = "workspace", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = ".gitattributes", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "favicon.ico", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = "go.sum", text = "", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = "pom.xml", text = "", fg_dark = "#343f44", fg_light = "#343f44" },
  { name = "webpack", text = "󰜫", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = "vagrantfile$", text = "", fg_dark = "#4f585e", fg_light = "#4f585e" },
  { name = "unlicense", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = "tmux.conf.local", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = "settings.gradle", text = "", fg_dark = "#475258", fg_light = "#475258" },
  { name = ".dockerignore", text = "󰡨", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = "sym-lib-table", text = "", fg_dark = "#d3c6aa", fg_light = "#d3c6aa" },
  { name = "_gvimrc", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = "kdenliverc", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
]

cords = [
  { name = "*.zip", text = "", fg_dark = "#d699b6", fg_light = "#d699b6" },
  { name = "*.tar", text = "", fg_dark = "#d699b6", fg_light = "#d699b6" },
  { name = "*.tar.gz", text = "", fg_dark = "#d699b6", fg_light = "#d699b6" },
  { name = "*.tar.xz", text = "", fg_dark = "#d699b6", fg_light = "#d699b6" },
  { name = "*.tar.bz2", text = "", fg_dark = "#d699b6", fg_light = "#d699b6" },
  { name = "*.7z", text = "", fg_dark = "#d699b6", fg_light = "#d699b6" },
  { name = "*.rar", text = "", fg_dark = "#d699b6", fg_light = "#d699b6" },

  { name = "*.jpg", text = "", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = "*.jpeg", text = "", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = "*.png", text = "", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = "*.gif", text = "", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = "*.svg", text = "", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = "*.webp", text = "", fg_dark = "#83c092", fg_light = "#83c092" },

  { name = "*.mp3", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = "*.mp4", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = "*.avi", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = "*.mkv", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = "*.mov", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = "*.flac", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = "*.wav", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },

  { name = "*.txt", text = "", fg_dark = "#d3c6aa", fg_light = "#d3c6aa" },
  { name = "*.md", text = "", fg_dark = "#d3c6aa", fg_light = "#d3c6aa" },
  { name = "*.pdf", text = "", fg_dark = "#e67e80", fg_light = "#e67e80" },
  { name = "*.doc", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = "*.docx", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },

  { name = "*.js", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = "*.ts", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = "*.py", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = "*.java", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "*.c", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = "*.cpp", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = "*.h", text = "", fg_dark = "#d699b6", fg_light = "#d699b6" },
  { name = "*.hpp", text = "", fg_dark = "#d699b6", fg_light = "#d699b6" },
  { name = "*.rs", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "*.go", text = "", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = "*.sh", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = "*.fish", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = "*.zsh", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },

  { name = "*.html", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "*.css", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = "*.json", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = "*.xml", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "*.yml", text = "", fg_dark = "#d699b6", fg_light = "#d699b6" },
  { name = "*.yaml", text = "", fg_dark = "#d699b6", fg_light = "#d699b6" },
  { name = "*.toml", text = "", fg_dark = "#d699b6", fg_light = "#d699b6" },
  { name = "*.ini", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = "*.conf", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
]

dirs = [
  { name = ".git", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "node_modules", text = "", fg_dark = "#e67e80", fg_light = "#e67e80" },
  { name = ".vscode", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = ".config", text = "", fg_dark = "#d699b6", fg_light = "#d699b6" },
  { name = "src", text = "", fg_dark = "#7fbbb3", fg_light = "#7fbbb3" },
  { name = "target", text = "", fg_dark = "#e69875", fg_light = "#e69875" },
  { name = "build", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = "dist", text = "", fg_dark = "#a7c080", fg_light = "#a7c080" },
  { name = "public", text = "", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = "assets", text = "", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = "images", text = "", fg_dark = "#83c092", fg_light = "#83c092" },
  { name = "docs", text = "", fg_dark = "#d3c6aa", fg_light = "#d3c6aa" },
  { name = "test", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
  { name = "tests", text = "", fg_dark = "#dbbc7f", fg_light = "#dbbc7f" },
]
