# Everforest theme for btop
# Based on https://github.com/sainnhe/everforest

# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#FFFFFF", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#2d353b"

# Main text color
theme[main_fg]="#d3c6aa"

# Title color for boxes
theme[title]="#a7c080"

# Higlight color for keyboard shortcuts
theme[hi_fg]="#83c092"

# Background color of selected items
theme[selected_bg]="#475258"

# Foreground color of selected items
theme[selected_fg]="#d3c6aa"

# Color of inactive/disabled text
theme[inactive_fg]="#7a8478"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#d3c6aa"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#83c092"

# Cpu box outline color
theme[cpu_box]="#56635f"

# Memory/disks box outline color
theme[mem_box]="#56635f"

# Net up/down box outline color
theme[net_box]="#56635f"

# Processes box outline color
theme[proc_box]="#56635f"

# Box divider line and small boxes line color
theme[div_line]="#475258"

# Temperature graph colors
theme[temp_start]="#a7c080"
theme[temp_mid]="#dbbc7f"
theme[temp_end]="#e67e80"

# CPU graph colors
theme[cpu_start]="#83c092"
theme[cpu_mid]="#7fbbb3"
theme[cpu_end]="#d699b6"

# Mem/Disk free meter
theme[free_start]="#a7c080"
theme[free_mid]=""
theme[free_end]=""

# Mem/Disk cached meter
theme[cached_start]="#7fbbb3"
theme[cached_mid]=""
theme[cached_end]=""

# Mem/Disk available meter
theme[available_start]="#dbbc7f"
theme[available_mid]=""
theme[available_end]=""

# Mem/Disk used meter
theme[used_start]="#e69875"
theme[used_mid]="#e67e80"
theme[used_end]=""

# Download graph colors
theme[download_start]="#83c092"
theme[download_mid]="#7fbbb3"
theme[download_end]="#d699b6"

# Upload graph colors
theme[upload_start]="#a7c080"
theme[upload_mid]="#dbbc7f"
theme[upload_end]="#e69875"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#a7c080"
theme[process_mid]="#dbbc7f"
theme[process_end]="#e67e80"
